name: Release node package
on:
  release:
    types: [created]
  push:
    tags:
      - "v-*"
jobs:
  build:
    name: Release application to npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        check-latest: true
        cache: yarn
        registry-url: 'https://registry.npmjs.org'
    - name: Download dependencies
      run: yarn install --silent  --immutable

    - name: Check lint issues
      run: yarn lint
    - name: Run all tests
      run: yarn test
    - name: Build the package
      run: yarn build
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: dist/*
        retention-days: 90